version: '3.8'
networks:
  ip6net:
    enable_ipv6: true
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: social
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
      - 3306
  nestjs:
    build: .
    image: social-be:v1
    ports:
      - "3000:3000"
    expose:
      - 3000
    restart: always
    environment:
      - DB_HOST=database
      - DB_PORT=3306
    depends_on:
      - database
    volumes:
      - db_data:/var/lib/mysql
    command: yarn start:dev
   nginx:
     build: ./nginx
     image: nginx:latest
     ports:
       - "8080:80"
     depends_on:
       - nestjs
       - database
  reactjs:
    image: social-fe:v1
    ports:
      - "5173:5173"
    expose:
      - 5173
    restart: always
    command: yarn start
    depends_on:
      - nestjs
    volumes:
      - ./client:/app
  # ngrok:
  #   image: ngrok/ngrok
  #   ports:
  #     - "4040:4040"
  #   restart: always
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #   command:
  #     - "start"
  #     - "--config"
  #     - "./etc/ngrok.yml"
  #     - "--all"
  #   depends_on:
  #     - nestjs
  #   links:
  #     - nestjs
volumes:
  db_data: